## AirBnb Investment Project 

**by  
Abdurrahman Therwi and 
Mohammad Alqarni


### Step 1: Cleaning Data Set

In [ ]:
# Load Pandas into Python
import pandas as pd
# from matplotlib import pyplot as plt
import matplotlib as plt

%matplotlib inline

In [ ]:
# load data set from Airban.csv file to variable 

AirbnbDS = pd.read_csv('Airbnb.csv')

**Check data loaded by show sample from AirbnbDS.**

In [14]:
AirbnbDS.sample()

,id,name,summary,space,host_id,host_url,host_name,host_since,host_location,host_about,...,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
3261,3119991,"""Charming English Studio_Bike Tour""",Our new charming studio has a home away from h...,Our classic townhouse was built in the 1950s i...,15744022,https://www.airbnb.com/users/show/15744022,Khuyay,5/19/14,"Washington, District of Columbia, United States","We love to see the world, not just to travel b...",...,12,6/27/14,9/4/15,93.0,10.0,10.0,10.0,10.0,7.0,8.0

**Shows information of loaded DataSet.**

In [13]:
AirbnbDS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3723 entries, 0 to 3722
Data columns (total 64 columns):
id                             3723 non-null int64
name                           3723 non-null object
summary                        3457 non-null object
space                          2977 non-null object
host_id                        3723 non-null int64
host_url                       3723 non-null object
host_name                      3723 non-null object
host_since                     3723 non-null object
host_location                  3717 non-null object
host_about                     2763 non-null object
host_response_time             3289 non-null object
host_response_rate             3289 non-null object
host_acceptance_rate           3109 non-null object
host_is_superhost              3723 non-null object
host_thumbnail_url             3723 non-null object
host_picture_url               3723 non-null object
host_neighbourhood             3461 non-null object
host_listings_count            3723 non-null int64
host_total_listings_count      3723 non-null int64
host_has_profile_pic           3723 non-null object
host_identity_verified         3723 non-null object
street                         3723 non-null object
neighbourhood                  3370 non-null object
city                           3723 non-null object
state                          3723 non-null object
zipcode                        3714 non-null object
market                         3723 non-null object
country_code                   3723 non-null object
latitude                       3723 non-null float64
longitude                      3723 non-null float64
is_location_exact              3723 non-null object
property_type                  3722 non-null object
room_type                      3723 non-null object
accommodates                   3723 non-null int64
bathrooms                      3696 non-null float64
bedrooms                       3702 non-null float64
beds                           3712 non-null float64
square_feet                    82 non-null float64
price                          3723 non-null object
weekly_price                   2124 non-null object
monthly_price                  1807 non-null object
security_deposit               1426 non-null object
cleaning_fee                   2335 non-null object
guests_included                3723 non-null int64
extra_people                   3723 non-null object
minimum_nights                 3723 non-null int64
maximum_nights                 3723 non-null int64
calendar_updated               3723 non-null object
has_availability               3723 non-null object
availability_30                3723 non-null int64
availability_60                3723 non-null int64
availability_90                3723 non-null int64
availability_365               3723 non-null int64
calendar_last_scraped          3723 non-null object
number_of_reviews              3723 non-null int64
first_review                   2893 non-null object
last_review                    2893 non-null object
review_scores_rating           2855 non-null float64
review_scores_accuracy         2848 non-null float64
review_scores_cleanliness      2847 non-null float64
review_scores_checkin          2847 non-null float64
review_scores_communication    2851 non-null float64
review_scores_location         2851 non-null float64
review_scores_value            2851 non-null float64
dtypes: float64(13), int64(13), object(38)
memory usage: 1.8+ MB

In [15]:
#show the dataset type  using
type(AirbnbDS)

pandas.core.frame.DataFrame

In [18]:
# print the top 5 rows in Data set 

AirbnbDS.head()

# also can you print the any number of rows depends on parameter
# AirbnbDS.head(10)

,id,name,summary,space,host_id,host_url,host_name,host_since,host_location,host_about,...,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
0,7087327,Historic DC Condo-Walk to Capitol!,Professional pictures coming soon! Welcome to ...,NaN,15830506,https://www.airbnb.com/users/show/15830506,Lize & Greg,5/21/14,"Washington, District of Columbia, United States","We are two fun, friendly entrepreneurs living ...",...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,975833,Spacious Capitol Hill Townhouse,NaN,Beautifully renovated Capitol Hill townhouse. ...,5338703,https://www.airbnb.com/users/show/5338703,Sebastian,3/5/13,"New York, New York, United States","Hi I'm Sebastian. \r\nAfter ten years in DC, m...",...,65,3/22/13,9/28/15,94.0,10.0,9.0,10.0,10.0,9.0,9.0
2,8249488,Spacious/private room for single,This is an ideal room for a single traveler th...,NaN,1487418,https://www.airbnb.com/users/show/1487418,Craig,12/9/11,"Washington, District of Columbia, United States",just ask,...,1,9/10/15,9/10/15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,8409022,A wonderful bedroom with library,Prime location right on the Potomac River in W...,NaN,16970249,https://www.airbnb.com/users/show/16970249,Christopher,6/18/14,"Washington, District of Columbia, United States",NaN,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8411173,Downtown Silver Spring,"Hi travellers! I live in this peaceful spot, b...",This is a 750 sq ft 1 bedroom 1 bathroom. Whi...,30369828,https://www.airbnb.com/users/show/30369828,Joshua,3/31/15,"Baltimore, Maryland, United States",NaN,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
l